/**
 * @file Automatically generated by barrelsby.
 */

export * from "./brand-icons/icon-discord";
export * from "./brand-icons/icon-docker";
export * from "./brand-icons/icon-facebook";
export * from "./brand-icons/icon-figma";
export * from "./brand-icons/icon-github";
export * from "./brand-icons/icon-gitlab";
export * from "./brand-icons/icon-gmail";
export * from "./brand-icons/icon-medium";
export * from "./brand-icons/icon-notion";
export * from "./brand-icons/icon-skype";
export * from "./brand-icons/icon-slack";
export * from "./brand-icons/icon-stripe";
export * from "./brand-icons/icon-telegram";
export * from "./brand-icons/icon-trello";
export * from "./brand-icons/icon-whatsapp";
export * from "./brand-icons/icon-zoom";
